# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9474886a44ec1d02612490355aab313714a702c1477a2c1eeebbb0b57feaf45c6b5c6f10dbe1753906003c6e381c7d1562da76f272f766ece48d794f52af2890

test:
  secret_key_base: 92d6ce8d6b5c1277aae38acb687619be6d1fc77fe1d1b35ec633dc25d9ff99c9e34584819d022d3bee844a19058b1dec6dd8df6b1004bbe675ec4f4c0a47d657

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
